-- 10. Drop table for PUNTOS_USUARIO
DROP TABLE IF EXISTS PUNTOS_USUARIO;

-- 9. Drop table for HISTORIAL_PUNTOS
DROP TABLE IF EXISTS HISTORIAL_PUNTOS;

-- 8. Drop table for USUARIOS_RETOS
DROP TABLE IF EXISTS USUARIOS_RETOS;

-- 7. Drop table for USUARIOS_EVENTOS
DROP TABLE IF EXISTS USUARIOS_EVENTOS;

-- 6. Drop table for USUARIOS_BENEFICIOS
DROP TABLE IF EXISTS USUARIOS_BENEFICIOS;


-- 5. Drop table for RETOS
DROP TABLE IF EXISTS RETOS;

-- 4. Drop table for BENEFICIOS
DROP TABLE IF EXISTS BENEFICIOS;

-- 3. Drop table for EVENTOS
DROP TABLE IF EXISTS EVENTOS;

-- Drop table for GLUCOSA
DROP TABLE IF EXISTS GLUCOSA;

-- Drop table for RITMO_CARDIACO
DROP TABLE IF EXISTS RITMO_CARDIACO;

-- Drop table for PRESION_ARTERIAL
DROP TABLE IF EXISTS PRESION_ARTERIAL;

-- Drop table for DATOS_SALUD
DROP TABLE IF EXISTS DATOS_SALUD;

-- 2. Drop table for USUARIOS
DROP TABLE IF EXISTS USUARIOS;

-- 1. Drop table for TIPO_USUARIO
DROP TABLE IF EXISTS TIPO_USUARIO;

DROP TABLE IF EXISTS FOTOS_PERFIL;
