-- 1. Insertar tipos de usuarios
INSERT INTO TIPO_USUARIO (DESCRIPCION) VALUES ('Empleado');
INSERT INTO TIPO_USUARIO (DESCRIPCION) VALUES ('Voluntario');


INSERT INTO FOTOS_PERFIL (ARCHIVO, DESCRIPCION) VALUES ('profile1','Voluntario1');
INSERT INTO FOTOS_PERFIL (ARCHIVO, DESCRIPCION) VALUES ('profile2','Voluntario2');
INSERT INTO FOTOS_PERFIL (ARCHIVO, DESCRIPCION) VALUES ('profile3','Voluntario3');
INSERT INTO FOTOS_PERFIL (ARCHIVO, DESCRIPCION) VALUES ('profile4','Voluntario4');
INSERT INTO FOTOS_PERFIL (ARCHIVO, DESCRIPCION) VALUES ('profile5','Voluntario5');
INSERT INTO FOTOS_PERFIL (ARCHIVO, DESCRIPCION) VALUES ('profile6','Voluntario6');
INSERT INTO FOTOS_PERFIL (ARCHIVO, DESCRIPCION) VALUES ('profile7','Voluntario7');
INSERT INTO FOTOS_PERFIL (ARCHIVO, DESCRIPCION) VALUES ('profile8','Voluntario8');
INSERT INTO FOTOS_PERFIL (ARCHIVO, DESCRIPCION) VALUES ('profile9','Voluntario9');



-- 2. Insertar usuarios
INSERT INTO USUARIOS (NOMBRE, A_PATERNO, A_MATERNO, CORREO, PASS, ID_TIPO_USUARIO, ID_FOTO) VALUES ('Juan', 'Pérez', 'Gómez', 'juan.perez@example.com', 'password', 1, 1);
INSERT INTO USUARIOS (NOMBRE, A_PATERNO, A_MATERNO, CORREO, PASS, ID_TIPO_USUARIO, ID_FOTO) VALUES ('Ana', 'López', 'Martínez', 'ana.lopez@example.com', 'password', 2, 2);
INSERT INTO USUARIOS (NOMBRE, A_PATERNO, A_MATERNO, CORREO, PASS, ID_TIPO_USUARIO, ID_FOTO) VALUES ('Carlos', 'Ramírez', 'Sánchez', 'carlos.ramirez@example.com', 'password', 1, 1);
INSERT INTO USUARIOS (NOMBRE, A_PATERNO, A_MATERNO, CORREO, PASS, ID_TIPO_USUARIO, ID_FOTO) VALUES ('María', 'Fernández', 'Rodríguez', 'maria.fernandez@example.com', 'password', 2, 1);
INSERT INTO USUARIOS (NOMBRE, A_PATERNO, A_MATERNO, CORREO, PASS, ID_TIPO_USUARIO, ID_FOTO) VALUES ('Lucía', 'Navarro', 'García', 'lucia.navarro@example.com', 'password', 1, 4);
INSERT INTO USUARIOS (NOMBRE, A_PATERNO, A_MATERNO, CORREO, PASS, ID_TIPO_USUARIO, ID_FOTO) VALUES ('Pedro', 'González', 'Torres', 'pedro.gonzalez@example.com', 'password', 2, 4);
INSERT INTO USUARIOS (NOMBRE, A_PATERNO, A_MATERNO, CORREO, PASS, ID_TIPO_USUARIO, ID_FOTO) VALUES ('Sofía', 'Hernández', 'Lopez', 'sofia.hernandez@example.com', 'password', 1, 3);
INSERT INTO USUARIOS (NOMBRE, A_PATERNO, A_MATERNO, CORREO, PASS, ID_TIPO_USUARIO, ID_FOTO) VALUES ('Miguel', 'Cruz', 'Mendoza', 'miguel.cruz@example.com', 'password', 2, 2);
INSERT INTO USUARIOS (NOMBRE, A_PATERNO, A_MATERNO, CORREO, PASS, ID_TIPO_USUARIO, ID_FOTO) VALUES ('AAA', 'BBB', 'CCC', 'aaa.bbb@example.com', 'password', 2, 1);

-- 3. Insertar eventos
INSERT INTO EVENTOS (NOMBRE, DESCRIPCION, NUM_MAX_ASISTENTES, PUNTAJE, FECHA) VALUES ('Conferencia de Tecnología', 'Una conferencia sobre las últimas tendencias en tecnología.', 100, 10, '2024-10-10 09:00:00');
INSERT INTO EVENTOS (NOMBRE, DESCRIPCION, NUM_MAX_ASISTENTES, PUNTAJE, FECHA) VALUES ('Seminario de Desarrollo Personal', 'Un seminario enfocado en el crecimiento personal y profesional.', 50, 8, '2024-10-15 14:00:00');
INSERT INTO EVENTOS (NOMBRE, DESCRIPCION, NUM_MAX_ASISTENTES, PUNTAJE, FECHA) VALUES ('Taller de Innovación', 'Un taller interactivo sobre innovación y creatividad.', 30, 15, '2024-11-05 11:00:00');
INSERT INTO EVENTOS (NOMBRE, DESCRIPCION, NUM_MAX_ASISTENTES, PUNTAJE, FECHA) VALUES ('Conferencia de Marketing', 'Tendencias actuales en marketing digital.', 75, 12, '2024-11-12 10:00:00');
INSERT INTO EVENTOS (NOMBRE, DESCRIPCION, NUM_MAX_ASISTENTES, PUNTAJE, FECHA) VALUES ('Taller de Trabajo en Equipo', 'Mejorar habilidades de trabajo en equipo.', 40, 10, '2024-12-01 09:30:00');
INSERT INTO EVENTOS (NOMBRE, DESCRIPCION, NUM_MAX_ASISTENTES, PUNTAJE, FECHA) VALUES ('Foro de Innovación Empresarial', 'Discusión sobre innovación en negocios.', 60, 18, '2024-12-15 15:00:00');

-- 4. Insertar beneficios
INSERT INTO BENEFICIOS (NOMBRE, DESCRIPCION, PUNTOS) VALUES ('Día libre', 'Un día libre extra para descansar.', 20);
INSERT INTO BENEFICIOS (NOMBRE, DESCRIPCION, PUNTOS) VALUES ('Descuento en la cafetería', 'Un 20% de descuento en todas las compras en la cafetería.', 5);
INSERT INTO BENEFICIOS (NOMBRE, DESCRIPCION, PUNTOS) VALUES ('Estacionamiento preferencial', 'Acceso a un espacio de estacionamiento preferencial.', 15);
INSERT INTO BENEFICIOS (NOMBRE, DESCRIPCION, PUNTOS) VALUES ('Vale de gasolina', 'Vale de gasolina por un mes.', 25);
INSERT INTO BENEFICIOS (NOMBRE, DESCRIPCION, PUNTOS) VALUES ('Suscripción a revista', 'Suscripción anual a una revista de negocios.', 10);
INSERT INTO BENEFICIOS (NOMBRE, DESCRIPCION, PUNTOS) VALUES ('Acceso a gimnasio', 'Acceso al gimnasio de la empresa.', 30);

-- 5. Insertar retos
INSERT INTO RETOS (NOMBRE, DESCRIPCION, PUNTAJE) VALUES ('Correr 10km', 'Completar un curso de 10 km.', 10);
INSERT INTO RETOS (NOMBRE, DESCRIPCION, PUNTAJE) VALUES ('Participar en 3 eventos', 'Asistir a 3 eventos diferentes organizados por la empresa.', 15);
INSERT INTO RETOS (NOMBRE, DESCRIPCION, PUNTAJE) VALUES ('Organizar un evento', 'Organizar un evento de inicio a fin.', 20);
INSERT INTO RETOS (NOMBRE, DESCRIPCION, PUNTAJE) VALUES ('Proponer una idea innovadora', 'Proponer y desarrollar una idea que mejore procesos de un evento.', 25);
INSERT INTO RETOS (NOMBRE, DESCRIPCION, PUNTAJE) VALUES ('Completar curso de liderazgo', 'Curso en línea sobre habilidades de liderazgo.', 15);
INSERT INTO RETOS (NOMBRE, DESCRIPCION, PUNTAJE) VALUES ('Mentorear a un nuevo empleado', 'Ser mentor de un nuevo empleado durante su primer mes.', 20);

-- 6. Insertar relación usuarios-beneficios
INSERT INTO USUARIOS_BENEFICIOS (USUARIO, BENEFICIO) VALUES (1, 1); -- Juan obtiene Día libre
INSERT INTO USUARIOS_BENEFICIOS (USUARIO, BENEFICIO) VALUES (2, 2); -- Ana obtiene Descuento en la cafetería
INSERT INTO USUARIOS_BENEFICIOS (USUARIO, BENEFICIO) VALUES (3, 3); -- Carlos obtiene Estacionamiento preferencial
INSERT INTO USUARIOS_BENEFICIOS (USUARIO, BENEFICIO) VALUES (4, 4); -- Lucía obtiene Vale de gasolina
INSERT INTO USUARIOS_BENEFICIOS (USUARIO, BENEFICIO) VALUES (5, 5); -- Pedro obtiene Suscripción a revista
INSERT INTO USUARIOS_BENEFICIOS (USUARIO, BENEFICIO) VALUES (6, 6); -- Sofía obtiene Acceso a gimnasio
INSERT INTO USUARIOS_BENEFICIOS (USUARIO, BENEFICIO) VALUES (7, 1); -- Miguel obtiene Día libre

-- 7. Insertar relación usuarios-eventos
INSERT INTO USUARIOS_EVENTOS (USUARIO, EVENTO, ASISTIO) VALUES (1, 1, 0); -- Juan asiste a Conferencia de Tecnología
INSERT INTO USUARIOS_EVENTOS (USUARIO, EVENTO, ASISTIO) VALUES (2, 2, 0);
INSERT INTO USUARIOS_EVENTOS (USUARIO, EVENTO, ASISTIO) VALUES (3, 3, 0);
INSERT INTO USUARIOS_EVENTOS (USUARIO, EVENTO, ASISTIO) VALUES (4, 4, 0);
INSERT INTO USUARIOS_EVENTOS (USUARIO, EVENTO, ASISTIO) VALUES (5, 5, 0);
INSERT INTO USUARIOS_EVENTOS (USUARIO, EVENTO, ASISTIO) VALUES (6, 6, 0);
INSERT INTO USUARIOS_EVENTOS (USUARIO, EVENTO, ASISTIO) VALUES (7, 1, 0);

-- 8. Insertar relación usuarios-retos
INSERT INTO USUARIOS_RETOS (ID, ID_RETO) VALUES (1, 1); -- Juan completa curso de 10 km
INSERT INTO USUARIOS_RETOS (ID, ID_RETO) VALUES (2, 2); -- Ana participa en 3 eventos
INSERT INTO USUARIOS_RETOS (ID, ID_RETO) VALUES (3, 3); -- Carlos organiza un evento
INSERT INTO USUARIOS_RETOS (ID, ID_RETO) VALUES (4, 4); -- Lucía propone una idea innovadora
INSERT INTO USUARIOS_RETOS (ID, ID_RETO) VALUES (5, 5); -- Pedro completa curso de liderazgo
INSERT INTO USUARIOS_RETOS (ID, ID_RETO) VALUES (6, 6); -- Sofía mentorea a un nuevo empleado
INSERT INTO USUARIOS_RETOS (ID, ID_RETO) VALUES (7, 2); -- Miguel participa en 3 eventos

-- 9. Insertar a historial de puntos
INSERT INTO HISTORIAL_PUNTOS (USUARIO, PUNTOS_MODIFICADOS, TIPO_MODIFICACION, BENEFICIO) VALUES (1, 50, 0, 1);
INSERT INTO HISTORIAL_PUNTOS (USUARIO, PUNTOS_MODIFICADOS, TIPO_MODIFICACION, RETO) VALUES (1, 50, 1, 1);
INSERT INTO HISTORIAL_PUNTOS (USUARIO, PUNTOS_MODIFICADOS, TIPO_MODIFICACION, EVENTO) VALUES (1, 50, 1, 1);
INSERT INTO HISTORIAL_PUNTOS (USUARIO, PUNTOS_MODIFICADOS, TIPO_MODIFICACION, EVENTO) VALUES (2, 50, 1, 2);

-- 10. Insertar puntos
INSERT INTO PUNTOS_USUARIO (USUARIO, PUNTOS_ACTUALES) VALUES (1, 100);
INSERT INTO PUNTOS_USUARIO (USUARIO, PUNTOS_ACTUALES) VALUES (2, 300);

-- 11. Insertar a datos de salud de usuario
INSERT INTO DATOS_SALUD (USUARIO, EDAD, TIPO_SANGRE, GENERO, PESO, ALTURA) VALUES (1, 30, 'O+', 'Masculino', 75.5, 1.75);
INSERT INTO DATOS_SALUD (USUARIO, EDAD, TIPO_SANGRE, GENERO, PESO, ALTURA) VALUES (2, 28, 'A-', 'Femenino', 65.0, 1.68);
INSERT INTO DATOS_SALUD (USUARIO, EDAD, TIPO_SANGRE, GENERO, PESO, ALTURA) VALUES (3, 35, 'B+', 'Masculino', 85.2, 1.80);
INSERT INTO DATOS_SALUD (USUARIO, EDAD, TIPO_SANGRE, GENERO, PESO, ALTURA) VALUES (4, 27, 'AB+', 'Femenino', 62.5, 1.65);
INSERT INTO DATOS_SALUD (USUARIO, EDAD, TIPO_SANGRE, GENERO, PESO, ALTURA) VALUES (5, 40, 'O-', 'Masculino', 90.0, 1.82);
INSERT INTO DATOS_SALUD (USUARIO, EDAD, TIPO_SANGRE, GENERO, PESO, ALTURA) VALUES (6, 22, 'A+', 'Femenino', 58.4, 1.70);
INSERT INTO DATOS_SALUD (USUARIO, EDAD, TIPO_SANGRE, GENERO, PESO, ALTURA) VALUES (7, 33, 'B-', 'Masculino', 78.0, 1.77);
INSERT INTO DATOS_SALUD (USUARIO, EDAD, TIPO_SANGRE, GENERO, PESO, ALTURA) VALUES (8, 29, 'AB-', 'Femenino', 64.2, 1.68);
INSERT INTO DATOS_SALUD (USUARIO, EDAD, TIPO_SANGRE, GENERO, PESO, ALTURA) VALUES (9, 31, 'O+', 'Masculino', 72.6, 1.73);

-- 12. Insertar Registro Presion Arterial
INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (1, '2024-09-15 08:30:00', 120, 80);
INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (1, '2024-09-16 08:30:00', 118, 78);
INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (1, '2024-09-17 08:30:00', 122, 82);
INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (1, '2024-09-18 08:30:00', 125, 85);
INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (1, '2024-09-19 08:30:00', 120, 80);
INSERT INTO PRESION_ARTERIAL (USUARIO, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (1, 130, 70);


INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (2, '2024-09-15 08:45:00', 115, 75);
INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (2, '2024-09-16 08:45:00', 117, 76);

INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (3, '2024-09-15 09:00:00', 125, 85);
INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (3, '2024-09-16 09:00:00', 130, 88);

INSERT INTO PRESION_ARTERIAL (USUARIO, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (4, 110, 70);
INSERT INTO PRESION_ARTERIAL (USUARIO, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (4, 112, 72);

INSERT INTO PRESION_ARTERIAL (USUARIO, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (5, 120, 80);
INSERT INTO PRESION_ARTERIAL (USUARIO, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (5, 118, 78);

INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (6, '2024-09-17 10:00:00', 125, 82);
INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (6, '2024-09-18 10:00:00', 122, 80);

INSERT INTO PRESION_ARTERIAL (USUARIO, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (7, 130, 85);
INSERT INTO PRESION_ARTERIAL (USUARIO, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (7, 128, 83);

INSERT INTO PRESION_ARTERIAL (USUARIO, FECHA, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (8, '2024-09-19 08:30:00', 115, 75);
INSERT INTO PRESION_ARTERIAL (USUARIO, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (8, 117, 76);

INSERT INTO PRESION_ARTERIAL (USUARIO, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (9, 122, 78);
INSERT INTO PRESION_ARTERIAL (USUARIO, PRESION_SISTOLICA, PRESION_DIASTOLICA) VALUES (9, 125, 80);


-- 12. Insertar Registro Ritmo Cardiaco
INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (1, '2024-09-15 08:30:00', 72);
INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (1, '2024-09-16 08:30:00', 70);
INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (1, '2024-09-17 08:30:00', 68);
INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (1, '2024-09-18 08:30:00', 75);
INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (1, '2024-09-19 08:30:00', 72);
INSERT INTO RITMO_CARDIACO (USUARIO, RITMO) VALUES (1, 74);

INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (2, '2024-09-15 08:45:00', 68);
INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (2, '2024-09-16 08:45:00', 70);

INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (3, '2024-09-15 09:00:00', 78);
INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (3, '2024-09-16 09:00:00', 80);

INSERT INTO RITMO_CARDIACO (USUARIO, RITMO) VALUES (4, 65);
INSERT INTO RITMO_CARDIACO (USUARIO, RITMO) VALUES (4, 67);

INSERT INTO RITMO_CARDIACO (USUARIO, RITMO) VALUES (5, 72);
INSERT INTO RITMO_CARDIACO (USUARIO, RITMO) VALUES (5, 74);

INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (6, '2024-09-17 10:00:00', 78);
INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (6, '2024-09-18 10:00:00', 76);

INSERT INTO RITMO_CARDIACO (USUARIO, RITMO) VALUES (7, 82);
INSERT INTO RITMO_CARDIACO (USUARIO, RITMO) VALUES (7, 80);

INSERT INTO RITMO_CARDIACO (USUARIO, FECHA, RITMO) VALUES (8, '2024-09-19 08:30:00', 70);
INSERT INTO RITMO_CARDIACO (USUARIO, RITMO) VALUES (8, 72);

INSERT INTO RITMO_CARDIACO (USUARIO, RITMO) VALUES (9, 75);
INSERT INTO RITMO_CARDIACO (USUARIO, RITMO) VALUES (9, 78);

-- 13. Insertar Registro Nivel de Glucosa
INSERT INTO GLUCOSA (USUARIO, FECHA, NIVEL) VALUES (1, '2024-09-15 08:30:00', 95);
INSERT INTO GLUCOSA (USUARIO, FECHA, NIVEL) VALUES (1, '2024-09-16 08:30:00', 92);
INSERT INTO GLUCOSA (USUARIO, FECHA, NIVEL) VALUES (1, '2024-09-17 08:30:00', 90);
INSERT INTO GLUCOSA (USUARIO, FECHA, NIVEL) VALUES (1, '2024-09-18 08:30:00', 94);
INSERT INTO GLUCOSA (USUARIO, NIVEL) VALUES (1, 93);

INSERT INTO GLUCOSA (USUARIO, FECHA, NIVEL) VALUES (2, '2024-09-15 08:45:00', 85);
INSERT INTO GLUCOSA (USUARIO, FECHA, NIVEL) VALUES (2, '2024-09-16 08:45:00', 88);

INSERT INTO GLUCOSA (USUARIO, FECHA, NIVEL) VALUES (3, '2024-09-15 09:00:00', 100);
INSERT INTO GLUCOSA (USUARIO, FECHA, NIVEL) VALUES (3, '2024-09-16 09:00:00', 102);

INSERT INTO GLUCOSA (USUARIO, NIVEL) VALUES (4, 85);
INSERT INTO GLUCOSA (USUARIO, NIVEL) VALUES (4, 87);

INSERT INTO GLUCOSA (USUARIO, NIVEL) VALUES (5, 92);
INSERT INTO GLUCOSA (USUARIO, NIVEL) VALUES (5, 90);

INSERT INTO GLUCOSA (USUARIO, FECHA, NIVEL) VALUES (6, '2024-09-17 10:00:00', 98);
INSERT INTO GLUCOSA (USUARIO, FECHA, NIVEL) VALUES (6, '2024-09-18 10:00:00', 95);

INSERT INTO GLUCOSA (USUARIO, NIVEL) VALUES (7, 100);
INSERT INTO GLUCOSA (USUARIO, NIVEL) VALUES (7, 102);

INSERT INTO GLUCOSA (USUARIO, FECHA, NIVEL) VALUES (8, '2024-09-19 08:30:00', 89);
INSERT INTO GLUCOSA (USUARIO, NIVEL) VALUES (8, 90);

INSERT INTO GLUCOSA (USUARIO, NIVEL) VALUES (9, 95);
INSERT INTO GLUCOSA (USUARIO, NIVEL) VALUES (9, 97);
